[General]
OutputDirectory = ~/TKAutoRipper/output
TempDirectory = ~/TKAutoRipper/temp

[CD]
OutputDirectory = ${General:OutputDirectory}/CD
OutputFormat = flac
ConfigPath = ~/TKAutoRipper/config/abcde.conf
AdditionalOptions =

[DVD]
OutputDirectory = ${General:OutputDirectory}/DVD
HandBrakePreset = Fast 480p30  # Preset or path to preset file for DVDs
HandBrakeFormat = mkv

[BLURAY]
OutputDirectory = ${General:OutputDirectory}/BLURAY
HandBrakePreset = Fast 1080p30  # Preset or path to preset file for Blu-rays
HandBrakeFormat = mkv

[OTHERDISK]
OutputDirectory = ${General:OutputDirectory}/ISO

[Drives]
Blacklist = /dev/sr420
DVDCapable = /dev/sr0
BlurayCapable = /dev/sr1

[Logging]
LogDirectory = /path/to/logs
LogLevel = INFO
