[General]
OutputDirectory = ~/TKAutoRipper/output
TempDirectory = ~/TKAutoRipper/temp

[CD]
ConfigPath = ~/TKAutoRipper/config/abcde.conf
OutputFormat = flac
AdditionalOptions =

[Video]
HandBrakePresetDVD = Fast 480p30  # Preset or path to preset file for DVDs
HandBrakeFormatDVD = mkv
HandBrakePresetBLURAY = Fast 1080p30  # Preset or path to preset file for Blu-rays
HandBrakeFormatBLURAY = mkv

[Drives]
Blacklist = # Drives to ignore: /dev/sr2, /dev/sr3

[Logging]
LogDirectory = /path/to/logs
LogLevel = INFO
